packages:
  - workbench/*
  - packages/*
  - docs

catalog:
  '@biomejs/biome': ^2.2.5
  '@types/node': 24.6.2
  '@vercel/functions': ^3.1.4
  '@vercel/oidc': ^3.0.3
  '@vitest/coverage-v8': ^3.2.4
  "nitro": "npm:nitro-nightly@3.1.0-20251025-144733-946505c1"
  ai: 5.0.76
  esbuild: ^0.25.11
  typescript: ^5.9.3
  vitest: ^3.2.4
  zod: 4.1.11
