/**
 * Types for workflow graph visualization
 * These match the structure generated by the SWC plugin in graph mode
 */

export interface Position {
  x: number;
  y: number;
}

export interface NodeMetadata {
  loopId?: string;
  loopIsAwait?: boolean;
  conditionalId?: string;
  conditionalBranch?: 'Then' | 'Else';
  parallelGroupId?: string;
  parallelMethod?: 'all' | 'race' | 'allSettled';
}

export interface NodeData {
  label: string;
  nodeKind: 'workflow_start' | 'workflow_end' | 'step';
  stepId?: string;
  line: number;
}

export interface GraphNode {
  id: string;
  type: string;
  position: Position;
  data: NodeData;
  metadata?: NodeMetadata;
}

export interface GraphEdge {
  id: string;
  source: string;
  target: string;
  type: 'default' | 'loop' | 'conditional' | 'parallel';
  label?: string;
}

export interface WorkflowGraph {
  workflowId: string;
  workflowName: string;
  filePath: string;
  nodes: GraphNode[];
  edges: GraphEdge[];
}

export interface WorkflowGraphManifest {
  version: string;
  workflows: Record<string, WorkflowGraph>;
}

/**
 * Types for overlaying execution data on workflow graphs
 */

export interface StepExecution {
  nodeId: string;
  stepId?: string;
  attemptNumber: number;
  status: 'pending' | 'running' | 'completed' | 'failed' | 'retrying';
  startedAt?: string;
  completedAt?: string;
  duration?: number;
  input?: unknown;
  output?: unknown;
  error?: { message: string; stack: string };
}

export interface EdgeTraversal {
  edgeId: string;
  traversalCount: number;
  lastTraversedAt?: string;
  timings: number[]; // time taken to traverse (ms)
}

export interface WorkflowRunExecution {
  runId: string;
  status: 'running' | 'completed' | 'failed' | 'pending' | 'cancelled';
  nodeExecutions: Map<string, StepExecution[]>; // nodeId -> array of executions (for retries)
  edgeTraversals: Map<string, EdgeTraversal>; // edgeId -> traversal info
  currentNode?: string; // for running workflows
  executionPath: string[]; // ordered list of nodeIds
}
