#!/usr/bin/env bash
# Re-run every check for the StartStamping model.
#
# For each variant cfg StartStamping_<v>.cfg (not the h_minus_* ablations):
#   results/<v>.txt                  core run with every invariant (stops at
#                                    the first violation; the ASSUME block at
#                                    the top prints every Layer-A invariant's
#                                    violating scenario classes, per caller
#                                    group, for the variant)
#   results/<v>__<AInv>.txt          Layer-A invariant, Init restricted to its
#                                    score-minimal violating scenario
#                                    (FocusInv); if it holds, all scenarios
#   results/<v>__<BInv>.txt          Layer-B invariant alone over every
#                                    scenario class (FocusInv = "LB"): BFS gives
#                                    the shortest counterexample
#   results/<v>__default__<BInv>.txt same, restricted to main-line callers
#                                    whose stamp comes from start()'s own
#                                    resolution (ScenarioFilter = "default")
#   results/<v>__race_cancel__<BInv>.txt   + a run_cancelled racer,
#   results/<v>__race_recovery__<BInv>.txt + one crash after a committed
#                                    write and the v4 missing-run-event
#                                    recovery; both on world-vercel targets
#                                    that attest (RaceScope = "attesting")
#                                    to keep the state space tractable. Per
#                                    invariant for the key variants (c, f, g,
#                                    h, i, k); one combined run for the others.
# For each ablation StartStamping_h_minus_<Fix>.cfg:
#   results/<v>.txt, results/<v>__race_cancel.txt,
#   results/<v>__race_recovery.txt   combined runs (first violation only)
# For each ProbeCache timing cfg PC_<name>.cfg (ProbeCache.tla):
#   results/PC_<name>.txt            one run: NoLongFallbackRun and/or the
#                                    liveness properties the cfg lists
# results/summary.txt                verdict + compact trace per result file
#                                    (digest.py)
#
# Env overrides: TLA2TOOLS (path to tla2tools.jar), JAVA, TLC_WORKERS.
set -u
cd "$(dirname "$0")"
TLA2TOOLS="${TLA2TOOLS:-$HOME/.local/opt/tla2tools.jar}"
JAVA="${JAVA:-java}"
WORKERS="${TLC_WORKERS:-2}"
TLC=("$JAVA" -XX:+UseParallelGC -Xmx2g -cp "$TLA2TOOLS" tlc2.TLC -workers "$WORKERS")
AINVS="NoOverStamp CallerCap CallerCapExplicit AttrGateMatchesStamp AttributesGateCorrect TargetCanReadInput StampRunnable CallerCanReadOwnStamp"
BINVS="NoBrick NoAvoidableBrick NoMixedIdentityLog NoStuck NoAvoidableStuck NoResurrect SpecNeverLowered SingleRunCreated NoOverRaise CallerCanReadResult"
DEFAULT_BINVS="NoAvoidableBrick NoMixedIdentityLog NoAvoidableStuck CallerCanReadResult"
RACE_BINVS="NoAvoidableBrick NoMixedIdentityLog NoAvoidableStuck NoResurrect SpecNeverLowered SingleRunCreated"
RACE_PER_INV="c_4327_4366_1044 f_floor6_10s_allfixes g_floor6_10s_notcommitted_reread h_floor6_10s_recommended i_recommended_envdrift k_4327_4366_head"
ONLY="${ONLY:-}"   # optional: run only variants whose name matches this regex

[[ -z "$ONLY" ]] && rm -rf results generated
mkdir -p results generated
run() { # <cfg> <result-name>
  local meta
  meta="$(mktemp -d)"
  echo ">>> $2"
  timeout 900 "${TLC[@]}" -metadir "$meta" -config "$1" StartStamping.tla \
    > "results/$2.txt" 2>&1
  local rc=$?
  echo "exit=$rc" >> "results/$2.txt"
  grep -E "^Error: Invariant|No error has been found|distinct states found" \
    "results/$2.txt" | tail -2 | sed 's/^/    /'
  rm -rf "$meta"
}
# gen <src-cfg> <out-name> <invariants> [CONST=value ...]
gen() {
  local src="$1" out="$2" invs="$3"; shift 3
  local body
  body="$(sed -n '/^CONSTANTS/,/^SPECIFICATION/p' "$src" | grep -v -E '^(CONSTANTS|SPECIFICATION)')"
  for kv in "$@"; do
    local k="${kv%%=*}" v="${kv#*=}"
    body="$(echo "$body" | sed -E "s|^    $k = .*|    $k = $v|")"
  done
  {
    echo "\\* generated by run.sh from $src ($*)"
    echo "CONSTANTS"
    echo "$body"
    echo "SPECIFICATION Spec"
    echo "VIEW View"
    echo "CHECK_DEADLOCK FALSE"
    echo "INVARIANTS"
    echo "    TypeOK"
    for i in $invs; do echo "    $i"; done
  } > "generated/$out.cfg"
  run "generated/$out.cfg" "$out"
}
RACE_CANCEL=('RaceScope="attesting"' 'CancelEnabled=TRUE')
RACE_RECOVERY=('RaceScope="attesting"' 'RecoveryEnabled=TRUE' 'MaxCrashes=1')

for cfg in StartStamping_*.cfg; do
  v="${cfg#StartStamping_}"; v="${v%.cfg}"
  [[ -n "$ONLY" && ! "$v" =~ $ONLY ]] && continue
  invs="$(sed -n '/^INVARIANTS/,$p' "$cfg" | grep -v -E '^(INVARIANTS|    TypeOK)$' | tr -d ' ' | tr '\n' ' ')"
  run "$cfg" "$v"
  case "$v" in
  h_minus_*)
    gen "$cfg" "${v}__race_cancel" "$invs" 'FocusInv="LB"' "${RACE_CANCEL[@]}"
    gen "$cfg" "${v}__race_recovery" "$invs" 'FocusInv="LB"' "${RACE_RECOVERY[@]}"
    continue ;;
  esac
  for inv in $AINVS; do gen "$cfg" "${v}__${inv}" "$inv" "FocusInv=\"$inv\""; done
  for inv in $BINVS; do gen "$cfg" "${v}__${inv}" "$inv" 'FocusInv="LB"'; done
  for inv in $DEFAULT_BINVS; do
    gen "$cfg" "${v}__default__${inv}" "$inv" 'FocusInv="LB"' 'ScenarioFilter="default"'
  done
  if [[ " $RACE_PER_INV " == *" $v "* ]]; then
    for inv in $RACE_BINVS; do
      gen "$cfg" "${v}__race_cancel__${inv}" "$inv" 'FocusInv="LB"' "${RACE_CANCEL[@]}"
      gen "$cfg" "${v}__race_recovery__${inv}" "$inv" 'FocusInv="LB"' "${RACE_RECOVERY[@]}"
    done
  else
    gen "$cfg" "${v}__race_cancel" "$RACE_BINVS" 'FocusInv="LB"' "${RACE_CANCEL[@]}"
    gen "$cfg" "${v}__race_recovery" "$RACE_BINVS" 'FocusInv="LB"' "${RACE_RECOVERY[@]}"
  fi
done

# ProbeCache.tla: timing of #4327's probe cache (PC_<name>.cfg, one result
# each; invariants and liveness PROPERTIES as listed in the cfg).
if [[ -z "$ONLY" || "PC_" =~ $ONLY ]]; then
  for cfg in PC_*.cfg; do
    n="${cfg%.cfg}"
    meta="$(mktemp -d)"
    echo ">>> $n"
    timeout 900 "${TLC[@]}" -metadir "$meta" -config "$cfg" ProbeCache.tla \
      > "results/$n.txt" 2>&1
    echo "exit=$?" >> "results/$n.txt"
    grep -E "is violated|properties were violated|No error has been found|distinct states found" \
      "results/$n.txt" | tail -2 | sed 's/^/    /'
    rm -rf "$meta"
  done
fi

python3 digest.py > results/summary.txt
echo "wrote results/summary.txt"
