/**
 * workerd smoke test for the QuickJS workflow runtime.
 *
 * Proves that the QuickJS VM execution layer — the `quickjs-wasi` binary +
 * native extensions + core's VM serde bundle — instantiates and runs inside
 * Cloudflare's workerd runtime, where `node:vm` is unavailable. This is the
 * foundational guarantee behind the QuickJS runtime: if this passes, workflow
 * orchestrator code can execute on Workers.
 *
 * IMPORTANT (workerd asset loading): workerd bans runtime WASM compilation
 * from bytes (`WebAssembly.compile(bytes)` → "Wasm code generation disallowed
 * by embedder"). Core's default asset module base64-decodes the binaries and
 * compiles them at runtime — great for Node/Vercel (no filesystem), but it
 * does NOT work on workerd. So here we import the `.wasm` / `.so` binaries as
 * pre-compiled `WebAssembly.Module`s (wrangler/esbuild compiles them at bundle
 * time; `.so` is mapped to CompiledWasm via wrangler `rules`). This is the
 * asset-loading path a real Workers deployment must use. The VM serde bundle
 * is a plain JS string, so core's generated copy is reused directly.
 */
import { QuickJS } from 'quickjs-wasi';
// @ts-expect-error - wrangler `rules` maps .so to CompiledWasm
import encodingModule from 'quickjs-wasi/encoding.so';
// @ts-expect-error - .so → CompiledWasm
import headersModule from 'quickjs-wasi/headers.so';
// Pre-compiled WebAssembly.Module imports (compiled at bundle time, not runtime).
// @ts-expect-error - wrangler resolves .wasm to a WebAssembly.Module
import quickjsModule from 'quickjs-wasi/quickjs.wasm';
// @ts-expect-error - .so → CompiledWasm
import structuredCloneModule from 'quickjs-wasi/structured-clone.so';
// @ts-expect-error - .so → CompiledWasm
import urlModule from 'quickjs-wasi/url.so';
// @ts-expect-error - generated by `pnpm --filter @workflow/core build`
// eslint-disable-next-line import/no-unresolved
import { VM_SERDE_BUNDLE } from '../../../src/runtime/vm-serde-bundle.generated.js';

const FIXED_TIME = 1700000000000;

// Mirror core's quickjsExtensions, but with pre-compiled Modules.
const extensions = [
  { name: 'encoding', wasm: encodingModule as WebAssembly.Module },
  { name: 'headers', wasm: headersModule as WebAssembly.Module },
  { name: 'url', wasm: urlModule as WebAssembly.Module },
  {
    name: 'structured-clone',
    wasm: structuredCloneModule as WebAssembly.Module,
  },
];

async function runChecks() {
  const checks: Record<string, unknown> = {};
  const vm = await QuickJS.create({
    wasm: quickjsModule as WebAssembly.Module,
    memoryLimit: 256 * 1024 * 1024,
    extensions: extensions as any,
  });
  try {
    checks.create = { ok: true };

    // Mirror the runtime's VM bootstrap: seeded Math.random, deterministic
    // clock + ULID timestamp, then eval the serde bundle.
    vm.evalCode(
      `globalThis.__ulidTimestamp = ${FIXED_TIME};` +
        `globalThis.__currentTime = ${FIXED_TIME};` +
        `(function(){var R=Date;function D(){return arguments.length===0?new R(globalThis.__currentTime):new R(...arguments);}D.prototype=R.prototype;Object.setPrototypeOf(D,R);D.now=function(){return globalThis.__currentTime;};globalThis.Date=D;})();` +
        `Math.random = function(){ return 0.42; };`
    ).dispose();
    vm.evalCode(VM_SERDE_BUNDLE, 'vm-serde.js').dispose();
    checks.serdeBundleEval = { ok: true };

    // Round-trip structured values entirely in-VM. Exercises the native
    // extensions (encoding=TextEncoder, structured-clone) and the
    // proposal-arraybuffer-base64 reducers for typed arrays.
    {
      using h = vm.evalCode(
        `(function(){` +
          `var ser = globalThis[Symbol.for("workflow-serialize")];` +
          `var de = globalThis[Symbol.for("workflow-deserialize")];` +
          `var v = { ok:true, n:41+1, when:new Date(0), m:new Map([["a",1]]), bytes:new Uint8Array([1,2,3]) };` +
          `var bytes = ser(v);` +
          `var back = de(bytes);` +
          `return JSON.stringify({` +
          `  prefix: new TextDecoder().decode(bytes.subarray(0,4)),` +
          `  n: back.n, ok: back.ok, whenMs: back.when.getTime(),` +
          `  isDate: back.when instanceof Date,` +
          `  isMap: back.m instanceof Map, mA: back.m.get("a"),` +
          `  isBytes: back.bytes instanceof Uint8Array, b0: back.bytes[0], b2: back.bytes[2]` +
          `});` +
          `})()`
      );
      checks.serdeRoundTrip = JSON.parse(vm.dump(h) as string);
    }

    // Register + invoke a workflow function (mirrors how a compiled bundle
    // registers into __private_workflows) and read its deterministic clock.
    {
      vm.evalCode(
        `globalThis.__private_workflows = new Map();` +
          `globalThis.__private_workflows.set("wf", function(a,b){ return { sum:a+b, when: Date.now() }; });`
      ).dispose();
      using h = vm.evalCode(
        `JSON.stringify(globalThis.__private_workflows.get("wf")(2,3))`
      );
      checks.workflowInvoke = JSON.parse(vm.dump(h) as string);
    }

    // Async workflow + microtask drain (the suspend/complete model).
    {
      vm.evalCode(
        `globalThis.__r = undefined;` +
          `Promise.resolve((async function(){ return 7*6; })()).then(function(v){ globalThis.__r = v; });`
      ).dispose();
      let b: number;
      do {
        b = vm.executePendingJobs();
      } while (b > 0);
      using h = vm.evalCode('globalThis.__r');
      checks.asyncDrain = { ok: true, value: vm.dump(h) };
    }
  } finally {
    vm.dispose();
  }
  return checks;
}

function allOk(checks: Record<string, unknown>): boolean {
  const rt = checks.serdeRoundTrip as Record<string, unknown> | undefined;
  const wf = checks.workflowInvoke as Record<string, unknown> | undefined;
  const ad = checks.asyncDrain as Record<string, unknown> | undefined;
  return (
    !!rt &&
    rt.prefix === 'devl' &&
    rt.n === 42 &&
    rt.ok === true &&
    rt.whenMs === 0 &&
    rt.isDate === true &&
    rt.isMap === true &&
    rt.mA === 1 &&
    rt.isBytes === true &&
    rt.b0 === 1 &&
    rt.b2 === 3 &&
    !!wf &&
    wf.sum === 5 &&
    wf.when === FIXED_TIME &&
    !!ad &&
    ad.value === 42
  );
}

export default {
  async fetch(): Promise<Response> {
    try {
      const checks = await runChecks();
      const ok = allOk(checks);
      return new Response(
        JSON.stringify({ ok, runtime: 'workerd', checks }, null, 2),
        {
          status: ok ? 200 : 500,
          headers: { 'content-type': 'application/json' },
        }
      );
    } catch (e) {
      return new Response(
        JSON.stringify({
          ok: false,
          error: e instanceof Error ? `${e.message}\n${e.stack}` : String(e),
        }),
        { status: 500, headers: { 'content-type': 'application/json' } }
      );
    }
  },
};
