[package]
name = "workflow-world-core"
version.workspace = true
edition.workspace = true
publish.workspace = true
authors.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
workflow-protocol = { path = "../workflow-protocol" }

[dev-dependencies]
serde_json.workspace = true
