import { Context, SQSEvent } from 'aws-lambda';
/**
 * Lambda handler for processing workflow and step queue messages.
 *
 * This follows the same architecture as Vercel's workflow implementation:
 * - SQS queues trigger this Lambda (like Vercel Queue triggers functions)
 * - Messages are converted to Request objects with queue metadata
 * - The appropriate handler (flow or step) is called directly
 * - Handlers are generated by workflowEntrypoint() and stepEntrypoint()
 */
export declare function handler(
  event: SQSEvent,
  context: Context
): Promise<{
  batchItemFailures: {
    itemIdentifier: string;
  }[];
}>;
