# gen NAME "overrides (K=V lines)" "INVARIANTS..." "PROPERTIES..."
gen() {
  local name=$1 over=$2 invs=$3 props=$4
  declare -A C=(
    [MaxV]=9 [StructuralSet]="{6, 7}" [CapabilitySet]="{3, 4, 5, 8}" [Rule]='"default"'
    [InitVersions]="{1, 2, 3, 4, 5, 6, 7, 8}" [ExecVersions]="{6, 7, 8}" [D]="{1, 2}"
    [Serial]=TRUE [ReaderCode]=8 [CallerCode]=8 [MaxLog]=4 [MaxAttempts]=1
    [StaleReads]=FALSE [CallerSplit]=FALSE [ResilientStart]=FALSE [CancelEnabled]=FALSE
    [Turbo]=FALSE [Recovery]=FALSE [InsertMayFail]=FALSE
    [FixResilient]=FALSE [FixRetrySkips]=FALSE [FixCancelGuard]=FALSE [FixGuardStart]=FALSE
    [FixRecovery]=FALSE [CompressGate]='"run"' )
  while IFS='=' read -r k v; do [ -n "$k" ] && C[$k]="$v"; done <<<"$over"
  {
    echo "\\* $name (generated by gen-configs.sh)"
    echo "SPECIFICATION Spec"
    echo "CONSTANTS"
    for k in MaxV StructuralSet CapabilitySet Rule InitVersions ExecVersions D ReaderCode CallerCode MaxLog MaxAttempts StaleReads CallerSplit ResilientStart CancelEnabled Turbo Recovery InsertMayFail Serial FixResilient FixRetrySkips FixCancelGuard FixGuardStart FixRecovery CompressGate; do
      echo "  $k = ${C[$k]}"
    done
    for i in $invs; do echo "INVARIANTS $i"; done
    for p in $props; do echo "PROPERTIES $p"; done
  } > "$name.cfg"
}

# genfc NAME "overrides" "INVARIANTS..." "PROPERTIES..."  (ForceClaimGate)
genfc() {
  local name=$1 over=$2 invs=$3 props=$4
  declare -A C=( [VictimCode]=8 [Minted]="{6, 8}" [CallerWorlds]="{6, 7, 8}"
    [ExplicitStamps]="{}" [GateThreshold]=8 [CliReuse]=TRUE [StaleStart]=FALSE
    [FixGuardStart]=FALSE )
  while IFS='=' read -r k v; do [ -n "$k" ] && C[$k]="$v"; done <<<"$over"
  {
    echo "\\* $name (generated by gen-configs.sh)"
    echo "SPECIFICATION Spec"
    echo "CONSTANTS"
    for k in VictimCode Minted CallerWorlds ExplicitStamps GateThreshold CliReuse StaleStart FixGuardStart; do
      echo "  $k = ${C[$k]}"
    done
    for i in $invs; do echo "INVARIANTS $i"; done
    for p in $props; do echo "PROPERTIES $p"; done
  } > "$name.cfg"
}
