import { join } from 'node:path';
import { semver, serve } from 'bun';
import { LocalBuilder } from './builders';
import { workflowTransformPlugin } from './plugin';

// Routes are only supported in Bun 1.2.3+
const REQUIRED_BUN_VERSION = '1.2.3';

const validVersion = semver.satisfies(Bun.version, `>=${REQUIRED_BUN_VERSION}`);

// Verify if the Bun version is supported
if (!validVersion) {
  throw new Error(
    `@workflow/bun requires Bun version >=${REQUIRED_BUN_VERSION}.`
  );
}

// Build and register the generated workflow routes from builder
await createWorkflowRoutes();

// Registers the plugin with Bun runtime
Bun.plugin(workflowTransformPlugin());

/**
 * Build and register the generated workflow routes from
 * builder with a patched Bun.serve
 */
async function createWorkflowRoutes() {
  // Build the workflow bundles/routes
  await new LocalBuilder().build();

  const cwd = process.cwd();

  // Workflow routes generated by the builder
  const defaultRoutes = {
    '/.well-known/workflow/v1/flow': await import(
      join(cwd, '.workflows/workflows.js')
    ),
    '/.well-known/workflow/v1/step': await import(
      join(cwd, '.workflows/steps.js')
    ),
    '/.well-known/workflow/v1/webhook': await import(
      join(cwd, '.workflows/webhook.js')
    ),
  };

  Bun.serve = (config) => {
    (config.routes as any) = {
      ...(config.routes as any),
      ...defaultRoutes,
    };
    return serve(config);
  };
}
