import { join } from 'node:path';
import { serve } from 'bun';
import { LocalBuilder } from './builders';
import { workflowTransformPlugin } from './plugin';

// Build the workflow bundles/routes
await new LocalBuilder().build();

// Registers the plugin with Bun runtime
Bun.plugin(workflowTransformPlugin());

// Register workflow routes
registerWorkflowRoutes();

/**
 * Register the generated workflow routes from builder
 * with a patched Bun.serve
 */
async function registerWorkflowRoutes() {
  const cwd = process.cwd();

  // Workflow routes generated by the builder
  const defaultRoutes = {
    '/.well-known/workflow/v1/flow': await import(
      join(cwd, '.workflows/workflows.js')
    ),
    '/.well-known/workflow/v1/step': await import(
      join(cwd, '.workflows/steps.js')
    ),
    '/.well-known/workflow/v1/webhook': await import(
      join(cwd, '.workflows/webhook.js')
    ),
  };

  Bun.serve = (config) => {
    (config.routes as any) = {
      ...(config.routes as any),
      ...defaultRoutes,
    };
    return serve(config);
  };
}
